[package]
name = "generic-ec-curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec-core = { path = "../generic-ec-core" }

subtle = { version = "2.4", default-features = false }
rand_core = { version = "0.6", default-features = false }
zeroize = { version = "1.5", default-features = false }

elliptic-curve = { version = "0.12", features = ["sec1", "hash2curve"], optional = true }
k256 = { version = "0.12", optional = true, features = ["hash2curve"] }
p256 = { version = "0.12", optional = true, features = ["hash2curve"] }
sha2 = { version = "0.10", optional = true }

[features]
default = []

rust-crypto = ["elliptic-curve"]
secp256k1 = ["rust-crypto", "k256", "sha2"]
secp256r1 = ["rust-crypto", "p256", "sha2"]
