[package]
name = "generic-ec-curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-ec-core = { path = "../generic-ec-core" }

subtle = { version = "2.4", default-features = false }
zeroize = { version = "1.5", default-features = false }
elliptic-curve = { version = "0.12", features = ["sec1"] }
rand_core = { version = "0.6", default-features = false }
