[workspace]
resolver = "2"
members = [
  "generic-ec",
  "generic-ec-core",
  "generic-ec-curves",
  "generic-ec-zkp",
  "wasm/wasm-example",
  "tests",
]
exclude = [
  "wasm/nostd",
]

[patch.crates-io.udigest]
git = "https://github.com/dfns/udigest"
branch = "small-improvements"
