name: Check README

on:
  pull_request:
    branches: [ "*" ]
    
env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-rdme
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cargo-rdme
    - name: Check that readme matches lib.rs
      run: |
        cargo rdme -w generic-ec -r README.md --check
        cargo rdme -w generic-ec-zkp -r generic-ec-zkp/README.md --check
        cargo rdme -w generic-ec-curves -r generic-ec-curves/README.md --check
        cargo rdme -w generic-ec-core -r generic-ec-core/README.md --check
