name: Check README

permissions:
  contents: read

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
    - name: Install cargo-rdme
      uses: baptiste0928/cargo-install@8195d4f734a149db85385bb4102b42efcd373759 #v3.5.0
      with:
        crate: cargo-rdme
        version: "=1.5.1"
    - name: Check that readme matches lib.rs
      run: |
        (cd generic-ec; cargo rdme -r ../README.md --check)
        (cd generic-ec-zkp; cargo rdme -r README.md --check)
        (cd generic-ec-curves; cargo rdme -r README.md --check)
        (cd generic-ec-core; cargo rdme -r README.md --check)
