# Run some workflows on ubuntu 22.04 because ubuntu-latest broke some system
# libs in late 2024

name: Rust

permissions:
  contents: read

on:
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  RUSTFLAGS: -D warnings

jobs:
  check-nostd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Check no-std
      run: cargo check -p generic-ec --no-default-features
  check-alloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Check with `alloc` only
      run: cargo check -p generic-ec --no-default-features --features alloc
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Check all-features
      run: cargo check -p generic-ec --all-features
  check-all:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Check everything
      run: cargo check --all-targets
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Run tests
      run: cargo test --all-features --workspace
  test-nostd:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Run tests
      run: cargo test --no-default-features --workspace
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - name: Check formatting
      run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Run clippy
      run: cargo clippy --all --lib --workspace --all-features --exclude generic-ec-tests -- --no-deps -D clippy::all -D clippy::unwrap_used -D clippy::expect_used
  clippy-nostd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Run clippy no-std
      run: cargo clippy -p generic-ec --no-default-features -- -D clippy::all
  clippy-tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Run clippy tests
      run: cargo clippy --workspace --tests --all-features -- -D clippy::all
  check-doc:
    runs-on: ubuntu-22.04
    steps:
    - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2 #nightly
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Check docs
      run: RUSTDOCFLAGS="--cfg docsrs -D warnings" cargo +nightly doc --workspace --all-features --no-deps
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Install wasm32-unknown-unknown toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build on wasm32-unknown-unknown
      run:
        cargo check -p generic-ec --target wasm32-unknown-unknown --features all-curves
    - name: Install wasm-pack
      uses: baptiste0928/cargo-install@77fc781ff2a66b362d815793ec7bd69b50d0e549 #v1
      with:
        crate: wasm-pack
    - name: wasm-pack an example project
      run: (cd wasm/wasm-example; wasm-pack build)
  build-wasm-nostd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae #v2
      with:
        cache-on-failure: "true"
    - name: Install wasm32-unknown-unknown toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build on wasm32-unknown-unknown (no_std)
      run:
        (cd wasm/nostd && cargo build -p nostd-example --target wasm32-unknown-unknown)
  check-semver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
        - generic-ec
        - generic-ec-core
        - generic-ec-curves
        - generic-ec-zkp
        feature-group:
        - all-features
        - only-explicit-features
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239 #v2
      with:
        package: ${{ matrix.package }}
        feature-group: ${{ matrix.feature-group }}
  check-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
    - name: Check changelogs
      run: ./.github/changelog.sh
